### ISSUE TITLE
The definition of alias MY_TYPE is not needed

### ISSUE THREAD

**Issue by nordlow** [andrewlalis/dvec#1]
The

```d
public alias MY_TYPE = Vec!(T, size);
```

at

https://github.com/andrewlalis/dvec/blob/main/source/dvec/vector.d#L30

is unnecessary. Instead you can refer to type of `this` inside of `Vec` using either `Vec` or the more generic `typeof(this)`.

**Comment by andrewlalis** [comment]
Interesting; I didn't know that! I'll update it this evening. Or maybe for documentation's sake it would just be clearer if I go back to the full template type. At the moment ddoc isn't too smart about how it presents aliases and other things, and I'm preferring the more readable solution in most cases.

**Comment by nordlow** [comment]
> Interesting; I didn't know that! I'll update it this evening. Or maybe for documentation's sake it would just be clearer if I go back to the full template type. At the moment ddoc isn't too smart about how it presents aliases and other things, and I'm preferring the more readable solution in most cases.

Yes, I too prefer `Vec` in this case.

**Comment by andrewlalis** [comment]
Reverted to `Vec!(T, size)`, and also reverted the similar change in matrix.d
